# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Colitu.Colitu
PackageVersion: 2.8.5
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: inno
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ElevationRequirement: elevatesSelf
ProductCode: '{B7B06C4E-1D5A-482F-A781-0F6C6C8A2B67}_is1'
ReleaseDate: 2026-10-10
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/colitu/windows/releases/download/v2.8.5/ColituVPN-Setup-2.8.5-x64.exe
  InstallerSha256: 40FC336A8BD5281A32EA729146A46D8A426DA15B4EF28BE1ABCF613E9B5670D8
ManifestType: installer
ManifestVersion: 1.12.0
